[package]
name = "scene_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# use flatbuffers as scene file encoder and decoder
[dependencies.flatbuffers]
version = "*"

